# Python for Data Analysis

## NumPy Operations

* Array with Arrays
* Array with Scalars
* Universal Array Functions

In [1]:
import numpy as np 

In [2]:
arr = np.arange(0,11)

In [3]:
 arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr + arr  # Addition ({PITFALL} Add != Concatenation)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr - arr # Subtraction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr * arr # Product

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [10]:
 arr + 100 # Scalar addition 

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [11]:
arr - 100 # Scalar subtraction

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [13]:
# NumPy won't throw errors if you multiply by zero like Python does

In [14]:
1/0  # Python error

ZeroDivisionError: division by zero

In [16]:
arr / arr  # NumPy throws warnings (First element is a nan, the rest get an output)

/Users/Josembi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [17]:
1/arr # infinity (inf) fo

/Users/Josembi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])