# Python for Data Analysis - NumPy 

## NumPy Arrays 

I'll import numpy then start by generating numbers using numpy

Get to speed with built in functions:
 * arange
 * linspace
 * Identity matrices using numpy 
 * random vector arrays and matrices using 'rand' and 'randn' fns
 * 

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [8]:
np.array(my_list) # Cast a list as an array

array([1, 2, 3])

In [10]:
arr = np.array(my_list)

In [11]:
arr

array([1, 2, 3])

In [15]:
'''
Casting a list of list which 
will be transformed to a matrix
'''
my_mat = [[1,2,3], [4,5,6], [7,8,9]] 

In [16]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
six_by_six_matrix = [[1,2,3,4,5,6], [2,4,1,0,5,3], [2,1,4,7,0,9], [3,4,2,6,7,0], [1,0,6,3,1,1], [6,5,4,3,2,1]]

In [23]:
six_by_six_matrix  
# Amazing what tech can do. I used to do this manually. 
# Let's see if I'll find the determinant 
# That's a 2 dimentional arrays with 6 rows and six columns

[[1, 2, 3, 4, 5, 6],
 [2, 4, 1, 0, 5, 3],
 [2, 1, 4, 7, 0, 9],
 [3, 4, 2, 6, 7, 0],
 [1, 0, 6, 3, 1, 1],
 [6, 5, 4, 3, 2, 1]]

In [33]:
np.arange(0,10)  
# Get an array from a range
# Returns 10 digits but starts from the 
# 1st index which is '0'


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# Supposing I want all the even numbers from 0 to 10 
# with a step size of 2 (skipping two digits)
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [38]:
# Suppose I want to generate an array of zeros
# Will return a one dimentional vector
np.zeros(3)

array([0., 0., 0.])

In [44]:
# You can pass a tuple of the dimention that you want
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [55]:
# An array  of ones (vector)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [59]:
# An array  of 2d (matrix) ~ pass a tuple 
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
# linspace returns evenly spaced numbers over a specified interval.
# Start at 0, stop at 5 with 10 evenly spaced points
# Returns a 1d vector of 10 evenly spaced points from 0 to 5
np.linspace(0,5,10) 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [62]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [63]:
# Creating an identity matrix using numpy 
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
# An array of random numbers
np.random.rand(4)

array([0.82566927, 0.08199327, 0.13806019, 0.71381601])

In [71]:
# Matrix of 5x5 dim
np.random.rand(5,5)

array([[0.20591762, 0.90769422, 0.69836913, 0.32203874, 0.36749473],
       [0.98507522, 0.75837335, 0.28479197, 0.88845715, 0.80075365],
       [0.78424852, 0.36352381, 0.49241452, 0.39189281, 0.4160677 ],
       [0.09505876, 0.15028527, 0.7216515 , 0.7997774 , 0.06558715],
       [0.07988395, 0.95255856, 0.10853133, 0.89005622, 0.29295114]])

In [74]:
# Return a sample (or samples) from the "standard normal" distribution.
np.random.randn(2)

array([2.17981829, 0.97963636])

In [73]:
np.random.randn(4,4)

array([[-0.35798722, -0.50108953,  2.01927266, -0.45015419],
       [ 0.8478083 , -0.27158726,  0.36491031,  0.6296472 ],
       [-1.75983086,  1.39145723,  0.81761352,  2.54304476],
       [ 0.39205348,  0.47923705,  0.05024542, -0.51869357]])

In [77]:
# Return random integers from `low` (inclusive) to `high` (exclusive).

np.random.randint(1, 100) # random int btn 1 & 100

95

In [79]:
np.random.randint(1, 100, 10) # 3rd arg will output 10 integers

array([16, 48, 28, 19, 47, 63, 94, 49, 17, 86])

In [85]:
print("\n" * 5)

In [81]:
arr = np.arange(25)

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [83]:
ranarr = np.random.randint(0,50,10)

In [84]:
ranarr

array([ 2, 15, 12, 29, 38, 32, 15,  2, 36, 23])

We can use various operations on arrays.
1. **reshape** - Can be used on an existing arrays to modify it's characteristics. 

In [86]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [95]:
arr.reshape(5,5) 
# Becomes a 2d array
# Number of rows == Number of columns otherwise it will throw an error
# So 5 * 5 = 25  && ru

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])