# Python for Data Analysis

## NumPy Array Indexing

* Slice Notation
* Indexing a 2d array (matrix)
* Conditional selection


In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# Just as in a list, we can pass an index to print an object
arr[8]

8

In [9]:
# Slicing: Print from index 1 to 5
arr[1:5]

array([1, 2, 3, 4])

In [16]:
# Slicing: Print the first five objects
arr[:5]

array([0, 1, 2, 3, 4])

In [17]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [21]:
# Slicing: Start at 5 end at 10th index
arr[5:10]

array([5, 6, 7, 8, 9])

In [22]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [23]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

NumPy differ because of their ability to broadcast

In [26]:
# Will broadcast '100' to the first five digits.
arr[0:5] = 100

In [27]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [29]:
arr = np.arange(0,11)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
slice_of_arr = arr[0:6]

In [32]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [33]:
# Broadcast to 99
slice_of_arr[:] = 99

In [36]:
slice_of_arr # The reason is because python is referencing and not copying

array([99, 99, 99, 99, 99, 99])

In [35]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [38]:
# Using the copy method to actually copy the array
arr_copy = arr.copy()

In [39]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [40]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [41]:
arr_copy[:] = 100 # Broadcast everything to 100

In [42]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [43]:
arr # Original unaffected by the broadcast 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
print("\n" * 5)

Indexing a 2d Array (Matrices)

There are 2 formats for grabbing elements from a 2d matrix
* Double bracket format
* Single bracket format

In [59]:
arr_2d = np.array([[5,10, 10], [6,2,15], [12,4,10]])

In [60]:
arr_2d

array([[ 5, 10, 10],
       [ 6,  2, 15],
       [12,  4, 10]])

In [68]:
# Supposing I want to grab the 1st element (5)
# Using Double bracket notation (pass 1st col, 1st row)
# Index starts from zero
arr_2d[0][0]

5

In [69]:
arr_2d[2][2]

10

In [72]:
arr_2d[2][1] # 2nd col, 1st row

4

In [73]:
# Index an entire row 
arr_2d[0]

array([ 5, 10, 10])

In [74]:
# Using comma separation instead of bracket notation

In [75]:
arr_2d[2,2]

10

In [76]:
arr_2d[2,0]

12

In [97]:
arr_2d


array([[ 5, 10, 10],
       [ 6,  2, 15],
       [12,  4, 10]])

In [103]:
# Grabbing a sub matrix
# Grab all & slice col 2 then from row 1 to the end (drop col '0')
arr_2d[:2,1:] 

array([[10, 10],
       [ 2, 15]])

In [99]:
arr_2d[:2]

array([[ 5, 10, 10],
       [ 6,  2, 15]])

In [ ]:
print("\n" * 5)

Conditional selection of arrays 

Using a comparison operator on an array will return a boolean

In [105]:
arr = np.arange(1,11)

In [106]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
# Use a comparison operator to get elements that
# are more than 5 and return result as a bool
bool_arr = arr > 5  

In [109]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [110]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [113]:
arr[arr>5] # Will return only the Truthy elements of the array

array([ 6,  7,  8,  9, 10])

In [114]:
# Supposing I want to know all the elements of the array that are less than 3
arr[arr < 3]

array([1, 2])

In [129]:
arr_2d = np.arange(50).reshape(5,10)

In [130]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [131]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [134]:
arr_2d[2:8,4:10]

array([[24, 25, 26, 27, 28, 29],
       [34, 35, 36, 37, 38, 39],
       [44, 45, 46, 47, 48, 49]])